// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqinwmecsxjzlybxlkoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxaW53bWVjc3hqemx5Ynhsa29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NTA1MjUsImV4cCI6MjA1NzMyNjUyNX0.Vd44pwOOSNWrMAx7V7F_KpPqOK8c5nG2X-3QqVUYVF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);